apiVersion: apps/v1
kind: Deployment
metadata:
  name: hp-search-service
  labels:
    app: hp-search-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hp-search-service
  template:
    metadata:
      labels:
        app: hp-search-service
        version: v1
    spec:
      containers:
      - name: search-service
        image: hp-search-service:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: RUST_LOG
          value: "info"
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: search-service-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
data:
  config.yaml: |
    log_level: info
    max_results: 100
    cache_ttl: 300 