apiVersion: v1
kind: Service
metadata:
  name: hp-search-service
  labels:
    app: hp-search-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: hp-search-service
---
apiVersion: v1
kind: Service
metadata:
  name: hp-search-service-internal
  labels:
    app: hp-search-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: hp-search-service 